title: byoungju94
email: byoungju94@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://byoungju94.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  byoungju94
youtube_username: byoungju94

sample_image: /images/sample_image.jpg

author: Byoungju Park
copyright: "Byoungju Park"

plugins:
  - jekyll-feed